# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\capstone_project\lib\gui_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.bg = QtWidgets.QLabel(Form)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap(":/rec/blue_bg.png"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.iron_man_face = QtWidgets.QLabel(Form)
        self.iron_man_face.setGeometry(QtCore.QRect(520, 90, 1001, 771))
        self.iron_man_face.setText("")
        self.iron_man_face.setPixmap(QtGui.QPixmap(":/rec/iron_man_face.gif"))
        self.iron_man_face.setScaledContents(True)
        self.iron_man_face.setObjectName("iron_man_face")
        self.jarvis = QtWidgets.QLabel(Form)
        self.jarvis.setGeometry(QtCore.QRect(180, 700, 531, 291))
        self.jarvis.setText("")
        self.jarvis.setPixmap(QtGui.QPixmap(":/rec/jarvis"))
        self.jarvis.setScaledContents(True)
        self.jarvis.setObjectName("jarvis")
        self.time_base = QtWidgets.QLabel(Form)
        self.time_base.setGeometry(QtCore.QRect(170, 190, 191, 161))
        self.time_base.setText("")
        self.time_base.setPixmap(QtGui.QPixmap(":/rec/date.png"))
        self.time_base.setScaledContents(True)
        self.time_base.setObjectName("time_base")
        self.temp_base = QtWidgets.QLabel(Form)
        self.temp_base.setGeometry(QtCore.QRect(30, 40, 141, 131))
        self.temp_base.setText("")
        self.temp_base.setPixmap(QtGui.QPixmap(":/rec/date.png"))
        self.temp_base.setScaledContents(True)
        self.temp_base.setObjectName("temp_base")
        self.date = QtWidgets.QLabel(Form)
        self.date.setGeometry(QtCore.QRect(1560, 830, 341, 101))
        self.date.setObjectName("date")
        self.base = QtWidgets.QLabel(Form)
        self.base.setGeometry(QtCore.QRect(40, 370, 231, 171))
        self.base.setText("")
        self.base.setPixmap(QtGui.QPixmap(":/rec/date.png"))
        self.base.setScaledContents(True)
        self.base.setObjectName("base")
        self.temp_2 = QtWidgets.QLabel(Form)
        self.temp_2.setGeometry(QtCore.QRect(70, 80, 71, 51))
        self.temp_2.setObjectName("temp_2")
        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(210, 230, 121, 81))
        self.time.setObjectName("time")
        self.exitB = QtWidgets.QPushButton(Form)
        self.exitB.setGeometry(QtCore.QRect(1600, 130, 221, 71))
        self.exitB.setStyleSheet("background-image: url(:/rec/Exit.png);\n"
"border:none;")
        self.exitB.setText("")
        self.exitB.setObjectName("exitB")
        self.iron_man_gif = QtWidgets.QLabel(Form)
        self.iron_man_gif.setGeometry(QtCore.QRect(1570, 360, 251, 331))
        self.iron_man_gif.setText("")
        self.iron_man_gif.setPixmap(QtGui.QPixmap(":/rec/iron_man.gif"))
        self.iron_man_gif.setScaledContents(True)
        self.iron_man_gif.setObjectName("iron_man_gif")
        self.internet_speed = QtWidgets.QLabel(Form)
        self.internet_speed.setGeometry(QtCore.QRect(110, 420, 131, 61))
        self.internet_speed.setObjectName("internet_speed")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Basic Home AI"))
        self.date.setText(_translate("Form", "TextLabel"))
        self.temp_2.setText(_translate("Form", "TextLabel"))
        self.time.setText(_translate("Form", "TextLabel"))
        self.internet_speed.setText(_translate("Form", "TextLabel"))
import rec_rc
